### ISSUE TITLE
Feedback on week 8 project progress

### ISSUE THREAD

**Issue by devamanyu** [CS2113-AY1819S1-T16-1/main#80]
Subject: feedback on week 8 project progress

See [v1.1 progress guide](https://nuscs2113-ay1819s1.github.io/website/admin/project-w08-mid-v12.html) for more details of the activities mentioned below.
***Mid-milestone progress reports are FYI only. They are not graded.***

### Recommended progress for the upcoming milestone

- [x]  Issue labels set up e.g., `type.*`, `priority.*` (:heavy_check_mark: well done!)
- [x]  Milestones created: v1.2 v1.3 v1.4 [Please ensure milestones are setup until 'v1.4'] (:heavy_check_mark: well done!)
- [x]  Issues marked as `type.Story` e.g., [link](https://github.com/CS2113-AY1819S1-T16-1/main/issues/3) (:heavy_check_mark: well done!)
- [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/CS2113-AY1819S1-T16-1/main/issues/3) (:heavy_check_mark: well done!)
*  Milestone v1.2 planned
   -  [ ]  A suitable deadline set (:exclamation: try to do by next milestone)
   -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/CS2113-AY1819S1-T16-1/main/issues/2) (:heavy_check_mark: well done!)
   -  [ ]  Issues allocated to v1.3 e.g.,  (:exclamation: try to do by next milestone)
- [x]  Build passing (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

Tutor: @stephlewyh

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2018-10-11 02:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.
